# dist: trusty # KVM Setup

notifications:
  email: false

os:
  - linux
  - osx

language: go

go:
    - 1.11.x

env:
  - TEST_NO_FUSE=1 TEST_VERBOSE=1 TEST_SUITE=test_go_expensive
  - TEST_NO_FUSE=1 TEST_VERBOSE=1 TEST_SUITE=test_sharness_expensive

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y librados-dev; fi

install:
  - make install

script:
  - make $TEST_SUITE

# For docker containers

sudo: required

services:
  - docker
